version: 2

buildSteps: &buildSteps
  - checkout
  - run:
      name: install-npm
      command: npm install
  - run:
      name: build
      command: npm run build
  - run:
      name: test
      command: npm test

jobs:
  "node-10":
    docker:
      - image: circleci/node:10
    steps: *buildSteps

  "node-12":
    docker:
      - image: circleci/node:12
    steps: *buildSteps

  "node-14":
    docker:
      - image: circleci/node:14
    steps: *buildSteps


workflows:
  version: 2
  build:
    jobs:
      - "node-10"
      - "node-12"
      - "node-14"
